### ISSUE TITLE
Component: Location pill heart icon

### ISSUE THREAD

**Issue by dynasty2** [CotripperPlatform/CoTrip#51] opened 2019-12-06 18:51 UTC
![image](https://user-images.githubusercontent.com/53455521/70347754-3a5e2780-182f-11ea-91d9-b35b7481657d.png)

**Comment by dynasty2** [comment] 2019-12-06 18:53
![image](https://user-images.githubusercontent.com/53455521/70348043-d25c1100-182f-11ea-8288-e403ae74e007.png)

**Comment by ZakkMan** [comment] 2019-12-07 01:04
This is a dupe of #74, so I'm going to close it.

**Closed by ZakkMan** 2019-12-07 01:04 UTC
