### ISSUE TITLE
Component: Inbox Icon 

### ISSUE THREAD

**Issue by DallasLind** [CotripperPlatform/CoTrip#54] opened 2019-12-06 18:59 UTC
![image](https://user-images.githubusercontent.com/54752666/70348364-89f12300-1830-11ea-8c3a-8b3202a40af2.png)

**Comment by ZakkMan** [comment] 2019-12-07 01:04
This is a dupe of #74, so I'm going to close it

**Closed by ZakkMan** 2019-12-07 01:04 UTC
